export const TOGGLE_VISIBILITY_SIDEBAR = 'TOGGLE_VISIBILITY_SIDEBAR';
export const POSITION_SIDEBAR = 'POSITION_SIDEBAR';
export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR';
export const CHANGE_ACTIVE_SIDEBAR_ITEM = 'CHANGE_ACTIVE_SIDEBAR_ITEM';

export const DISMISS_ALERT = 'DISMISS_ALERT';

export const TOGGLE_STAR_STATUS = 'TOGGLE_STAR_STATUS';
export const SET_READ_STATUS = 'TOGGLE_READ_STATUS';
export const SET_SELECT_STATUS = 'SET_SELECT_STATUS';
export const DELETE_MAIL = 'DELETE_MAIL';
export const TOGGLE_ALL_CHECKED = 'TOGGLE_ALL_CHECKED';
export const CHANGE_FILTERED_MAILS = 'CHANGE_FILTERED_MAILS';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';
